---
apiVersion: v1
kind: Namespace
metadata:
  name: akka
  labels:
    name: akka
---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: "akka-sample-cluster-kubernetes-dns-scala"
  namespace: akka
  labels:
    appName: "akka-sample-cluster-kubernetes-dns-scala"
spec:
  replicas: 3
  selector:
    matchLabels:
      appName: "akka-sample-cluster-kubernetes-dns-scala"
#update
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
 #update
  template:
    metadata:
      labels:
        appName: "akka-sample-cluster-kubernetes-dns-scala"
    spec:
      restartPolicy: Always
      containers:
      - name: "akka-sample-cluster-kubernetes-dns-scala"
        image: "local/akka-sample-cluster-kubernetes-dns-scala:1.3.3.9"
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
        ports:
        - containerPort: 8558
          name: management
        - containerPort: 2552
          name: remoting
        volumeMounts: []
      volumes: []
---
#headless
apiVersion: v1
kind: Service
metadata:
  labels:
    appName: "akka-sample-cluster-kubernetes-dns-scala"
  #OLD minikube annotations:
    #service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: "akka-sample-cluster-kubernetes-dns-scala-internal"
  namespace: akka
spec:
  ports:
  - name: management
    port: 8558
    protocol: TCP
    targetPort: 8558
  - name: remoting
    port: 2552
    protocol: TCP
    targetPort: 2552
  selector:
    appName: "akka-sample-cluster-kubernetes-dns-scala"
  clusterIP: None
  publishNotReadyAddresses: true
#headless
---
#http-load-balancer
apiVersion: v1
kind: Service
metadata:
  labels:
    appName: "akka-sample-cluster-kubernetes-dns-scala"
  name: "akka-sample-cluster-kubernetes-dns-scala"
  namespace: akka
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8558
    protocol: TCP
    targetPort: 8558
  selector:
    appName: "akka-sample-cluster-kubernetes-dns-scala"
  type: LoadBalancer
#public
